#!/usr/bin/env node

/**
 * Interactive setup script for NEXS MCP Server
 *
 * This script guides users through initial configuration:
 * - Choose data directory (global vs workspace)
 * - Create element type directories
 * - Generate sample .env file
 * - Display next steps
 */

const fs = require('fs');
const path = require('path');
const readline = require('readline');

const rl = readline.createInterface({
	input: process.stdin,
	output: process.stdout
});

function question(query) {
	return new Promise((resolve) => rl.question(query, resolve));
}

async function main() {
	console.log('\n🚀 NEXS MCP Server - Initial Setup\n');
	console.log('This wizard will help you configure your NEXS MCP Server installation.\n');

	// Step 1: Choose data directory location
	console.log('📁 Data Directory Configuration\n');
	console.log('1. Workspace directory (.nexs-mcp in current workspace)');
	console.log('2. Global directory (~/.nexs-mcp for all projects)');
	console.log('3. Custom directory (specify path)\n');

	const choice = await question('Select option (1-3) [default: 1]: ');

	let dataDir;
	switch (choice.trim() || '1') {
		case '1':
			dataDir = path.join(process.cwd(), '.nexs-mcp');
			break;
		case '2':
			dataDir = path.join(require('os').homedir(), '.nexs-mcp');
			break;
		case '3':
			const customPath = await question('Enter custom directory path: ');
			dataDir = path.resolve(customPath.trim());
			break;
		default:
			console.log('❌ Invalid option. Using workspace directory.');
			dataDir = path.join(process.cwd(), '.nexs-mcp');
	}

	console.log(`\n✅ Data directory: ${dataDir}\n`);

	// Step 2: Create directory structure
	console.log('📂 Creating element directories...\n');

	const elementTypes = ['persona', 'skill', 'template', 'agent', 'memory', 'ensemble'];
	const elementsDir = path.join(dataDir, 'elements');

	try {
		fs.mkdirSync(elementsDir, { recursive: true });
		console.log(`✅ Created: ${elementsDir}`);

		for (const type of elementTypes) {
			const typeDir = path.join(elementsDir, type);
			fs.mkdirSync(typeDir, { recursive: true });
			console.log(`  ✅ Created: ${type}/`);
		}
	} catch (err) {
		console.error(`\n❌ Error creating directories: ${err.message}`);
		process.exit(1);
	}

	// Step 3: Generate .env file
	console.log('\n📝 Generating configuration file...\n');

	const envContent = `# NEXS MCP Server Configuration
# Generated by init-setup.js on ${new Date().toISOString()}

# Storage Configuration
NEXS_DATA_DIR=${dataDir}
NEXS_SERVER_NAME=nexs-mcp
NEXS_STORAGE_TYPE=file

# Logging Configuration
NEXS_LOG_LEVEL=info
NEXS_LOG_FORMAT=json

# Auto-save Configuration
NEXS_AUTO_SAVE_MEMORIES=true
NEXS_AUTO_SAVE_INTERVAL=5m

# Skill Extraction Configuration (IMPORTANT: sync by default)
NEXS_SKILL_EXTRACTION_ENABLED=true
NEXS_SKILL_EXTRACTION_AUTO_ON_CREATE=true
NEXS_SKILL_EXTRACTION_SKIP_DUPLICATES=true
NEXS_SKILL_EXTRACTION_MIN_NAME_LENGTH=3
NEXS_SKILL_EXTRACTION_MAX_PER_PERSONA=50
NEXS_SKILL_EXTRACTION_FROM_EXPERTISE=true
NEXS_SKILL_EXTRACTION_FROM_CUSTOM=true
NEXS_SKILL_EXTRACTION_AUTO_UPDATE=true

# Resources Configuration
NEXS_RESOURCES_ENABLED=true
NEXS_RESOURCES_CACHE_TTL=5m

# Compression Configuration
NEXS_COMPRESSION_ENABLED=true
NEXS_COMPRESSION_ALGORITHM=gzip
NEXS_COMPRESSION_MIN_SIZE=1024
NEXS_COMPRESSION_LEVEL=6
NEXS_COMPRESSION_ADAPTIVE=true

# Streaming Configuration
NEXS_STREAMING_ENABLED=true
NEXS_STREAMING_CHUNK_SIZE=10
NEXS_STREAMING_THROTTLE=50ms
NEXS_STREAMING_BUFFER_SIZE=100

# Summarization Configuration
NEXS_SUMMARIZATION_ENABLED=true
NEXS_SUMMARIZATION_AGE=168h
NEXS_SUMMARIZATION_MAX_LENGTH=500
NEXS_SUMMARIZATION_RATIO=0.3
NEXS_SUMMARIZATION_PRESERVE_KEYWORDS=true
NEXS_SUMMARIZATION_EXTRACTIVE=true

# Adaptive Cache Configuration
NEXS_ADAPTIVE_CACHE_ENABLED=true
NEXS_ADAPTIVE_CACHE_MIN_TTL=1h
NEXS_ADAPTIVE_CACHE_MAX_TTL=168h
NEXS_ADAPTIVE_CACHE_BASE_TTL=24h

# Prompt Compression Configuration
NEXS_PROMPT_COMPRESSION_ENABLED=true
NEXS_PROMPT_COMPRESSION_REMOVE_REDUNDANCY=true
NEXS_PROMPT_COMPRESSION_WHITESPACE=true
NEXS_PROMPT_COMPRESSION_ALIASES=true
NEXS_PROMPT_COMPRESSION_PRESERVE_STRUCTURE=true
NEXS_PROMPT_COMPRESSION_RATIO=0.65
NEXS_PROMPT_COMPRESSION_MIN_LENGTH=500
`;

	const envPath = path.join(process.cwd(), '.env.nexs-mcp');

	try {
		if (fs.existsSync(envPath)) {
			const overwrite = await question(`\n⚠️  File ${envPath} already exists. Overwrite? (y/N): `);
			if (overwrite.trim().toLowerCase() !== 'y') {
				console.log('Skipping .env file generation.');
			} else {
				fs.writeFileSync(envPath, envContent);
				console.log(`✅ Configuration file created: ${envPath}`);
			}
		} else {
			fs.writeFileSync(envPath, envContent);
			console.log(`✅ Configuration file created: ${envPath}`);
		}
	} catch (err) {
		console.error(`\n❌ Error creating .env file: ${err.message}`);
	}

	// Step 4: Display next steps
	console.log('\n' + '='.repeat(60));
	console.log('🎉 Setup Complete!');
	console.log('='.repeat(60) + '\n');

	console.log('📋 Next Steps:\n');
	console.log('1. Load environment variables:');
	console.log(`   export $(cat ${envPath} | grep -v '^#' | xargs)`);
	console.log('\n2. Start the MCP server:');
	console.log('   npx nexs-mcp');
	console.log('\n3. Create your first persona:');
	console.log('   Use MCP tool "create_persona" with your AI client');
	console.log('\n4. Skills will be automatically extracted when creating personas');
	console.log('   (if NEXS_SKILL_EXTRACTION_AUTO_ON_CREATE=true)\n');

	console.log('📚 Documentation:');
	console.log('   https://github.com/fsvxavier/nexs-mcp\n');

	console.log('💡 Tip: Add .env.nexs-mcp to your .gitignore if not already present.\n');

	rl.close();
}

main().catch((err) => {
	console.error(`\n❌ Setup failed: ${err.message}`);
	process.exit(1);
});
